name: Data Processing

on:
  push:
    branches:
      - main

jobs:
  data-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas gspread
        pip install -r requirements.txt
    - name: Create credentials file
      run: |
        echo "$GOOGLE_SHEETS_CREDENTIALS" > credentials.json
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

    - name: Run data script
      run: |
        python3 generator_danych.py -s 25566

    - name: Display report
      run: cat report.txt
