name: Data Processing

on:
  push:
    branches:
      - main

jobs:
  data-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas gspread
        pip install -r requirements.txt

    - name: Run data script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: |
        python3 generator_danych.py -s 25566

    - name: Display report
      run: cat report.txt
